name: Sync LICENSE.md from chatgpt-widescreen/opera/* to <platform>/*, then chatgpt-widescreen/opera/extension/* to chatgpt-widescreen/(chrome|edge)/extension/*, then chatgpt-widescreen/opera/extension/_locales/* to chatgpt-widescreen/<firefox/extension|greasemonkey>/_locales/*, then chatgpt-widescreen/* to adamlui/chatgpt-apps/chatgpt-widescreen/*, then chatgpt-widescreen/greasemonkey/* to adamlui/userscripts/chatgpt/chatgpt-widescreen/*

on:
  push:
    branches: [main]
    paths: [chatgpt-widescreen/opera/**]

jobs:
  build:
    if: (github.repository == 'adamlui/chatgpt-apps') && (github.event.commits[0].committer.username != 'kudo-sync-bot')
    runs-on: ubuntu-latest
    env:
      GIT_AUTHOR_NAME: ${{ github.event.commits[0].author.name }}
      GIT_AUTHOR_EMAIL: ${{ github.event.commits[0].author.email }}
      GIT_COMMITTER_NAME: kudo-sync-bot
      GIT_COMMITTER_EMAIL: auto-sync@kudoai.com

    steps:

      - name: Checkout adamlui/chatgpt-apps
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/chatgpt-apps
          path: adamlui/chatgpt-apps
          fetch-depth: 2

      - name: Checkout adamlui/chatgpt-widescreen
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/chatgpt-widescreen
          path: adamlui/chatgpt-widescreen

      - name: Checkout adamlui/userscripts
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/userscripts
          path: adamlui/userscripts

      - name: Sync LICENSE.md from chatgpt-widescreen/opera/* to chatgpt-widescreen/<platform>/*
        run: |
          cd ${{ github.workspace }}/adamlui/chatgpt-apps/chatgpt-widescreen
          platforms=($(find . -type d -name "docs" | # paths to docs/
            awk -F'/' '{print $(NF-1)}' | # filter to parents
            grep -v "^opera$")) # exclude opera
          echo "Platforms: ${platforms[@]}"
          languages=($(ls docs/*/LICENSE.md | # paths to LICENSEs
            awk -F'/' '{print $(NF-1)}') # filter to parents
            "en") # include English
          echo -e "Languages: ${languages[@]}\n"
          for lang in "${languages[@]}"; do
            opera_license=./opera$([[ "$lang" != "en" ]] && echo "/docs/$lang/" || echo "/")LICENSE.md
            opera_license_content=$(git show HEAD:"$opera_license")
            opera_license_modified=$(git log -1 --format="%ct" -- "$opera_license")
            for platform in "${platforms[@]}"; do
              platform_license=./$platform/$([[ "$lang" != "en" ]] && echo "docs/$lang/" || echo "")LICENSE.md
              platform_license_content=$(git show HEAD:"$platform_license")
              platform_license_modified=$(git log -1 --format="%ct" -- "$platform_license")
              if [[ $opera_license_modified -gt $platform_license_modified ]] ; then
                if [[ "$opera_license_content" != "$platform_license_content" ]] ; then
                  cp -f "$opera_license" "$platform_license"
                  echo "Copied $opera_license to $platform_license"
          fi ; fi ; done; done

      - name: Sync chatgpt-widescreen/opera/extension/* to chatgpt-widescreen/(chrome|edge)/extension/*
        run: |
          for browser in chrome edge
          do
            rsync -avhr --delete \
              "${{ github.workspace }}/adamlui/chatgpt-apps/chatgpt-widescreen/opera/extension/" \
              "${{ github.workspace }}/adamlui/chatgpt-apps/chatgpt-widescreen/$browser/extension/"
          done

      - name: Sync chatgpt-widescreen/opera/extension/_locales/* to chatgpt-widescreen/greasemonkey/_locales/*
        run: |
          rsync -avhr --delete \
            "${{ github.workspace }}/adamlui/chatgpt-apps/chatgpt-widescreen/opera/extension/_locales/" \
            "${{ github.workspace }}/adamlui/chatgpt-apps/chatgpt-widescreen/greasemonkey/_locales"

      - name: Sync chatgpt-widescreen/* to adamlui/chatgpt-widescreen/*
        run: |
          rsync -avhr --delete --filter={'P /.*','P /eslint*','P /package*.json'} \
            ${{ github.workspace }}/adamlui/chatgpt-apps/chatgpt-widescreen/ \
            ${{ github.workspace }}/adamlui/chatgpt-widescreen/

      - name: Sync chatgpt-widescreen/greasemonkey/* to adamlui/userscripts/chatgpt/chatgpt-widescreen/*
        run: |
          rsync -avhr --delete \
            ${{ github.workspace }}/adamlui/chatgpt-apps/chatgpt-widescreen/greasemonkey/ \
            ${{ github.workspace }}/adamlui/userscripts/chatgpt/chatgpt-widescreen/

      - name: Sync /chatgpt-widescreen/opera/extension/_locales/ to /chatgpt-widescreen/firefox/extension/_locales/
        run: |
          rsync -avhr --delete \
            "${{ github.workspace }}/adamlui/chatgpt-apps/chatgpt-widescreen/opera/extension/_locales/" \
            "${{ github.workspace }}/adamlui/chatgpt-apps/chatgpt-widescreen/firefox/extension/_locales"

      - name: Escape backticks in commit msg
        env:
          COMMIT_MSG: ${{ github.event.head_commit.message }}
        run: |
          echo "ESCAPED_MSG<<EOF" >> $GITHUB_ENV
          echo "$COMMIT_MSG" | sed 's/`/\`/g' >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Push changes to adamlui/chatgpt-apps
        run: |
          cd ${{ github.workspace }}/adamlui/chatgpt-apps
          git pull # again to sync w/ concurrent workflow updates
          git add .
          git commit -n -m "$ESCAPED_MSG ↞ [auto-sync from \`chatgpt-widescreen/opera\`]" || true
          git push

      - name: Push changes to adamlui/chatgpt-widescreen
        run: |
          cd ${{ github.workspace }}/adamlui/chatgpt-widescreen
          git pull # again to sync w/ concurrent workflow updates
          git add .
          git commit -n -m "$ESCAPED_MSG ↞ [auto-sync from \`adamlui/chatgpt-apps/chatgpt-widescreen/opera\`]" || true
          git push

      - name: Push changes to adamlui/userscripts
        run: |
          cd ${{ github.workspace }}/adamlui/userscripts
          git pull # again to sync w/ concurrent workflow updates
          git add .
          git commit -n -m "$ESCAPED_MSG ↞ [auto-sync from \`adamlui/chatgpt-apps/chatgpt-widescreen/opera\`]" || true
          git push
