name: Sync chatgpt-infinity/chrome/extension/ to chatgpt-infinity/(edge|opera)/extension/, then chatgpt-infinity/ to adamlui/chatgpt-infinity/

on:
  push:
    branches: [main]
    paths: [chatgpt-infinity/chrome/**]

jobs:
  build:
    if: (github.repository == 'adamlui/chatgpt-apps') && (github.event.commits[0].committer.username != 'kudo-sync-bot')
    runs-on: ubuntu-latest
    env:
      GIT_AUTHOR_NAME: ${{ github.event.commits[0].author.name }}
      GIT_AUTHOR_EMAIL: ${{ github.event.commits[0].author.email }}
      GIT_COMMITTER_NAME: kudo-sync-bot
      GIT_COMMITTER_EMAIL: auto-sync@kudoai.com

    steps:

      - name: Checkout adamlui/chatgpt-apps
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/chatgpt-apps
          path: adamlui/chatgpt-apps

      - name: Checkout adamlui/chatgpt-infinity
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/chatgpt-infinity
          path: adamlui/chatgpt-infinity

      - name: Sync /chatgpt-infinity/chrome/extension/ to /chatgpt-infinity/(edge|opera)/extension/
        run: |
          for browser in edge opera
          do
            rsync -avhr --delete \
              "${{ github.workspace }}/adamlui/chatgpt-apps/chatgpt-infinity/chrome/extension/" \
              "${{ github.workspace }}/adamlui/chatgpt-apps/chatgpt-infinity/$browser/extension/"
          done

      - name: Sync /chatgpt-infinity/ to adamlui/chatgpt-infinity/
        run: |
          rsync -avhr --delete --filter={'P /.*','P /eslint*','P /package*.json'} \
            ${{ github.workspace }}/adamlui/chatgpt-apps/chatgpt-infinity/ \
            ${{ github.workspace }}/adamlui/chatgpt-infinity/

      - name: Escape backticks in commit msg
        env:
          COMMIT_MSG: ${{ github.event.head_commit.message }}
        run: |
          echo "ESCAPED_MSG<<EOF" >> $GITHUB_ENV
          echo "$COMMIT_MSG" | sed 's/`/\`/g' >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Push changes to adamlui/chatgpt-apps
        run: |
          cd ${{ github.workspace }}/adamlui/chatgpt-apps
          git pull # again to sync w/ concurrent workflow updates
          git add .
          git commit -n -m "$ESCAPED_MSG ↞ [auto-sync from \`chatgpt-infinity/chrome\`]" || true
          git push

      - name: Push changes to adamlui/chatgpt-infinity
        run: |
          cd ${{ github.workspace }}/adamlui/chatgpt-infinity
          git pull # again to sync w/ concurrent workflow updates
          git add .
          git commit -n -m "$ESCAPED_MSG ↞ [auto-sync from \`adamlui/chatgpt-apps/chatgpt-infinity/chrome\`]" || true
          git push
