name: Update usercount + jsDelivr shields in root READMEs

on:
  schedule:
    - cron: "25 2 * * 0,2,4" # every Sun/Tue/Thu @ 2:25 AM

jobs:
  update-root-usercount-jsd-shields:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout adamlui/chatgpt-apps
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/chatgpt-apps
          path: adamlui/chatgpt-apps

      - name: Fetch/sum user counts
        id: get-stats
        run: |
          LC_NUMERIC=en_US # to insert commas

          declare -A gf_scripts=( # for Greasy Fork script user counts
            ["460805"]="Autoclear ChatGPT History"
            ["462440"]="BraveGPT"
            ["466789"]="ChatGPT Auto-Continue"
            ["462422"]="ChatGPT Auto Refresh"
            ["465051"]="ChatGPT Infinity"
            ["461473"]="ChatGPT Widescreen Mode"
            ["459849"]="DuckDuckGPT"
            ["478597"]="GoogleGPT"
          )

          declare -A chrome_extensions=( # for Chrome extension user counts
            ["amikeononomkhphopbflomhnmdijjpmb"]="ChatGPT Infinity"
            ["jgnjpnmofkalfliddjelaciggjgnphgm"]="ChatGPT Widescreen Mode"
          )

          declare -A edge_addons=( # for Edge addon user counts
            ["jgonecnbmehicpdpjkdekamhmlebfagb"]="ChatGPT Infinity"
            ["obnaaalnokmchdoagnhmllakaclaaooa"]="ChatGPT Widescreen Mode"
          )

          jsd_gh_repos=( # for jsDelivr request counts
            "adamlui/chatgpt-apps" "adamlui/autoclear-chatgpt-history" "adamlui/chatgpt-auto-continue"
            "adamlui/chatgpt-auto-refresh" "adamlui/chatgpt-infinity" "adamlui/chatgpt-widescreen"
            "KudoAI/bravegpt" "KudoAI/duckduckgpt" "KudoAI/googlegpt"
          )

          expand_num() { # expand nums abbreviated w/ 'k' or 'm' suffix to integers
            local num=$(echo "$1" | tr '[:upper:]' '[:lower:]') # convert to lowercase
            if [[ $num =~ k$ ]] ; then
              num="${num%k}" # remove 'k' suffix
              num=$(awk "BEGIN { printf \"%.0f\", $num * 1000 }") # multiply by 1000
            elif [[ $num =~ m$ ]] ; then
              num="${num%m}" # remove 'm' suffix
              num=$(awk "BEGIN { printf \"%.0f\", $num * 1000000 }") # multiply by 1000000
            fi ; echo "$num"
          }

          format_total() {
            local num=$1 ; first_digit="${num:0:1}" second_digit="${num:1:1}"
            second_digit_rounded=$(( second_digit < 5 ? 0 : 5 ))
            if (( num >= 1000000000 )) ; then # 1B+ w/ one decimal place
              formatted_num="$(( num / 1000000000 ))"
              remainder=$(( (num % 1000000000) / 100000000 ))
              if (( remainder != 0 )) ; then formatted_num+=".$remainder" ; fi
              formatted_num+="B+"
            elif (( num >= 10000000 )) ; then # abbr 10,000,000+ to 999,000,000+
              formatted_num=$(printf "%'.f+" $((( num / 1000000 ) * 1000000 )))
            elif (( num >= 1000000 )) ; then # abbr 1,000,000+ to 9,500,000+
              formatted_num="${first_digit},${second_digit}00,000+"
            elif (( num >= 100000 )) ; then # abbr 100,000+ to 950,000+
              formatted_num="${first_digit}${second_digit_rounded}0,000+"
            elif (( num >= 10000 )) ; then # abbr 10,000+ to 90,000+
              formatted_num="${first_digit}0,000+"
            elif (( num >= 1000 )) ; then # abbr 1K to 9.9K
              formatted_num="$(( num / 1000 ))"
              remainder=$(( (num % 1000) / 100 ))
              if (( remainder != 0 )) ; then formatted_num+=".$remainder" ; fi
              formatted_num+="K"
            else formatted_num="$num" ; fi # preserve <1K as is
            echo "$formatted_num"
          }

          # Alphabetize arrays for more readable logging
          for array_type in "gf_scripts" "chrome_extensions" "edge_addons" ; do

            # Extract IDs/names
            eval ids=\${!$array_type[@]} names=(\"\${$array_type[@]}\")
            IFS=' ' read -r -a ids <<< "$ids" # converted space-delimited IDs to actual array
            for ((i = 0 ; i < ${#ids[@]} ; i++)) ; do
              app_id="${ids[i]}" app_name="${names[i]}" ; done

            # Create alphabetized arrays
            sorted_array=()
            for ((i = 0; i < ${#ids[@]}; i++)) ; do
              sorted_array+=("${names[i]}:${ids[i]}") ; done
            IFS=$'\n' sorted_array=($(sort <<<"${sorted_array[*]}"))
            eval sorted_${array_type}=\(\"\${sorted_array[@]}\"\)
          done

          # Fetch/sum Greasy Fork user counts
          for tuple in "${sorted_gf_scripts[@]}" ; do
            script_id="${tuple##*:}" script_name="${tuple%%:*}"
            base_url="https://img.shields.io/greasyfork/dt/"
            gf_users=$(curl -s "$base_url$script_id" |
              sed -n 's/.*<title>installs: \([0-9.k]\+\)*<\/title>.*/\1/Ip')
            gf_users=$(expand_num "$gf_users")
            echo "$script_name GF users: $gf_users"
            total_gf_users=$((total_gf_users + gf_users))
          done ; echo -e "\n-----\nTotal Greasy Fork users: $total_gf_users\n-----\n"

          # Fetch/sum Chrome extension user counts
          for tuple in "${sorted_chrome_extensions[@]}" ; do
            app_id="${tuple##*:}" app_name="${tuple%%:*}"
            base_url="https://img.shields.io/chrome-web-store/users/"
            chrome_users=$(curl -s "$base_url$app_id" |
              sed -n 's/.*<title>users: \([0-9.k]\+\)*<\/title>.*/\1/Ip')
            chrome_users=$(expand_num "$chrome_users")
            echo "$app_name Chrome users: $chrome_users"
            total_chrome_users=$((total_chrome_users + chrome_users))
          done ; echo -e "\n-----\nTotal Chrome users: $total_chrome_users\n-----\n"

          # Fetch/sum Edge addon user counts
          for tuple in "${sorted_edge_addons[@]}" ; do
            app_id="${tuple##*:}" app_name="${tuple%%:*}"
            base_url="https://microsoftedge.microsoft.com/addons/getproductdetailsbycrxid/"
            edge_users=$(curl -s "$base_url$app_id" |
              grep -o '"activeInstallCount":[0-9]*' |
              sed 's/"activeInstallCount"://')
            echo "$app_name Edge users: $edge_users"
            total_edge_users=$((total_edge_users + edge_users))
          done ; echo -e "\n-----\nTotal Edge users: $total_edge_users\n-----\n"

          # Fetch/sum jsDelivr request counts
          for repo in "${jsd_gh_repos[@]}" ; do
            repo_requests=$(curl -s "https://img.shields.io/jsdelivr/gh/hm/$repo.svg" |
              sed -n -E 's|.*<title>jsdelivr: ([0-9,.km]+).*</title>.*|\1|Ip')
            repo_requests=$(expand_num "$repo_requests")
            echo "$repo jsDelivr hits: $repo_requests"
            total_requests=$((total_requests + repo_requests))
          done ; echo -e "\n-----\nTotal monthly jsDelivr requests: $total_requests\n-----\n"

          # Format totals
          formatted_total_users=$(format_total "$((
            total_gf_users + total_chrome_users + total_edge_users))")
          echo "Formatted total users: $formatted_total_users"
          formatted_total_requests=$(format_total "$total_requests")
          echo "Formatted total monthly jsDelivr requests: $formatted_total_requests"

          # Expose as outputs for update step next
          echo "total_users=$formatted_total_users" >> $GITHUB_OUTPUT
          echo "total_requests=$formatted_total_requests" >> $GITHUB_OUTPUT

      - name: Update README shields
        id: update-stats
        run: |
          cd ${{ github.workspace }}/adamlui/chatgpt-apps

          total_users="${{ steps.get-stats.outputs.total_users }}"
          total_requests="${{ steps.get-stats.outputs.total_requests }}"

          # Update usercount shields
          if [ "$total_users" == "0" ] ; then echo "Error getting total usercount"
          else
            for readme in $(find docs/ -name "README.md") ; do
              old_readme=$(<"$readme")
              sed -i "s/\(badge\/[^-]*-\)[0-9.,km+]\+-/\1$total_users-/gI" "$readme"
              new_readme=$(<"$readme")
              if [ "$old_readme" != "$new_readme" ] ; then users_updated=true ; fi
            done
            if [ "$users_updated" = true ] ; then echo "Usercount shields updated to $total_users"
            else echo "Usercount shields already up-to-date" ; fi
          fi

          # Update jsDelivr shields
          if [ "$total_requests" == "0" ] ; then echo "Error getting total jsDelivr requests"
          else
            for readme in $(find docs/ -name "README.md") ; do
              old_readme=$(<"$readme")
              sed -i -E "s|(badge/jsDelivr_[^-]+-)[0-9.,km+]+|\1$total_requests|Ig" "$readme"
              new_readme=$(<"$readme")
              if [ "$old_readme" != "$new_readme" ] ; then requests_updated=true ; fi
            done
            if [ "$requests_updated" = true ] ; then echo "jsDelivr shields updated to $total_requests"
            else echo "jsDelivr shields already up-to-date" ; fi
          fi

          # Define commit msg for push step next
          if [ "$users_updated" == "true" ] && [ "$requests_updated" == "true" ] ; then
            multi_shield_types_updated=true ; fi
          commit_msg="Updated "
          [ "$users_updated" == "true"              ] && commit_msg+="usercount"
          [ "$multi_shield_types_updated" == "true" ] && commit_msg+="/"
          [ "$requests_updated" == "true"           ] && commit_msg+="jsDelivr"
          commit_msg+=" shield counters"
          echo "commit_msg=$commit_msg" >> $GITHUB_OUTPUT # expose as output

      - name: Push to adamlui/chatgpt-apps
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          push_options: --force
          add_options: --all
          commit_user_email: auto-sync@kudoai.com
          commit_author: kudo-sync-bot <auto-sync@kudoai.com>
          commit_message: ${{ steps.update-stats.outputs.commit_msg }}
          file_pattern: "**/README.md"
          repository: adamlui/chatgpt-apps
